DNAstring = "CACGTGTTGTCAGAGCGGATACTAATTCGGCGCCAGCGAGGAGATCCCGTCGTTACACTCGGGAACCAAGTCCGAGAGAAAGCGTAGTGAGTCTGCCGAGAGGTGGGAAGTACAGCCGCACATTACGGCCGGTTTGCGCTCGCAGTGGCAGGGTGGTGGGGGTACGATATTTGGCAAATCTCGGGATGGAGTAGAACCTTCGCAAATGTCATGTCACCTATGTTACTCATTGTGGCGCGACAGCGCTCTGGTCGACAACCCGTCTAAGTGTTTACTAGGCTAATGCTCTGCCACCTAAGAGTGAACCAAAAGACGTGGCACACGGTTGCACATGCCTAGATTGTCCCTGACTTAGACTGAGAAACTACGGTCCCATTGTACGTTACCAGATTTAGACTGAGACAAGCTGGGTGAATTTCGTTGGGCGCGCGCAGGTGTGCTTTCAAGGGGAAGTTACTCTCTAGTGGAAGGTAGCCGTCGGTTGGGTTGCATAGCAAGCTTGGCCAATGTCTTATTGCAAGCAAAGTCACTGCCGAACGCCACTAATGTCTATACCCGACGTTAGGATTATGCGGCAGGTCATATTGCCTTAATCTAATGTCGGCTGCCCTCCAAATATTAGTATTATTCCAGAGCATAAGACGGGTCCCCCAAACTGAGCTCTCGAATTATTCCCCCATCCACGCTGGGCCGCGAGACTCGCGGAAAAAGTGATCGGCTGGATAGGGACGGTCACGCTCACGACCATCACTATAGCGCAAGGGAATTCAGTTTCAAGCATTCCCAGCCAGTAGAGATGTTCAGTGCTTGAGACTGAAGGCGAGCCATTTTCGCTCTGGCGTCATGTGGGGAATACAGATGATTTGAGATGCGCTAATGACTAAGCCTGGCTTGTTGGCCCGGAAGGATTGCGCGCGCTACATCATACCACGGTAGCACCGCGTATCCGGAGGCTTGTTGGACACATTCTATATTCATTTGCC"
RNAstring = ""

for letter in DNAstring:
    if letter == 'A':
        RNAstring += 'A'
    elif letter == 'G':
        RNAstring += 'G'
    elif letter == 'C':
        RNAstring += 'C'
    elif letter == 'T':
        RNAstring += 'U'
print(RNAstring)