DNAString = "CTATTTACATCAGGCTTGGACAGCCCTCTAACGCGGTTTGGTATTCATGTTTTAGCCGTAGGTGTAGGGCGAAGCTCTGGTTTATCGCCGTCCACATAATGTTTGACGGTTCACGGTGGTCGCATGTGTTGCTTCTGGGAAGAGGTCCTTGCACCACAGGGTGGAACAGACCCTACATGGCGCACCCAGACAGGCTTGTCCAGATGGAATACTTTGGAAAATACCATCGGCTATAGTGATCGCGGCACCGGTCAACCCAGCTCCGAGGGGGCTGAGCCCCGCATAAGAGCAAACTATGCGAACCCCTGACGGGTGCTGACTACATTAAATTTGAAATGACTGCGCGAAGGGTGACCTTTGCCTGTCCTAACAGGTCTTCTTTCGATAACCGATGAGGGCCTAAACCGGAAATATTCTGTGCTTAAAGATTCCCCCAGTCGCATATAGAATAAGCCTGTTCCATTCTTCTGTCTGCGACCATCCACTTGGTTACGCCCGAATTCACCAGTTGTCGAATGCGTTCGGCTGTCTACATTATACGCGCGTGCAAATTGTAGCAGCGGCAAGCTGTATGATTCAAAGAGCCCGGAGAAGGCGCGTGACGCGGGCGGGATGGACGGTGTAGCGCGTCGCAATGGCACGCCGTCAGGAAAGGCTTTCCACAGGGCGACTTTACTTACATACGATGTCGGTAGCTGAATAAGACGGATGCATAGGGACGTCAGGAGAATTTAGGTGTGTAAAATTCAATGTTCCGTACTGACTACCGTCGAGGGGTGGGTGGTGAGGTGGACCTCTAGGATACGTTCCTAAACTATTGGATAATTTTGCCGATGCACTTCACGTGAGGCGGGAAGTTGATTGCTCTTATCATGGCCTAGAATCTTGGGCTACTGGTAGGCTTTCGGGAGCCCCTGTTCCGACAACCTATATATTAGTAAGTAGGAGAGGATAGGTGTTCCAAGATCGTCAGCCCGAGTCCCTCGGACGTGGAT"
reverseString = DNAString[::-1]
compString = ""

for letter in reverseString:
    if letter == 'A':
        compString += 'T'
    elif letter == 'G':
        compString += 'C'
    elif letter == 'C':
        compString += 'G'
    elif letter == 'T':
        compString += 'A'
print(compString)