def align( si,sj ,score=1):
    d=[[0 for col in range( len( si )+1 )] for raw in range( len( sj ) +1)]
    path = []
    s = 0
    for i in range( 0,len(sj)):
        for j in range( 0,len( si ) ):
            if sj[i]==si[j]:
                delta=score
            else:
                delta=0
            d[i+1][j+1]=max( [d[i][j]+delta,d[i+1][j],d[i][j+1]] )
            if d[ i+1 ][ j+1 ] > d[ i ][ j ] and d[ i+1 ][ j+1 ] > d[i+1][j] and  d[ i+1 ][ j+1 ]> d[i][j+1] and d[ i+1 ][ j+1 ] > s:
                path.append( j ) 
                s = d[ i+1 ][ j+1 ]
    return path
 
 
s1 = """GGCCGACGGGGCTACTCAACGACACTGCCTTCAGGGACGTTACGATTCAAGTTAAAGAGT
GGACCATCATTTTAGGCAAATGGATATAGCGTCGAGTGGGGATACTGGAAGTACGTGCCA
CAGTGAGATTTCATACCTCCCTGGATTCGAGACAAAAGAATTCCGGGTATACAACCGTGA
ACGGAGTCTGAACCAGGGCCTCTACTTATCATCGTCCCGACTAGGCTGTTCCATGAATCA
GTGGGTACTCGGTGTAAAATTGTGCTATACACCCATATCCTAATGGCCCGAGACATCTAT
TGCCACCTGATAGCTCGTCTCGACGAATGTTTAAGCAAGGAGTGAAACATCAAACGGTGC
CTATTTAGGTAACTGAGAAATGGTACATCAAGGAGGCATGGTTGGAGTTAACGGACCAGT
TCGTCGATGGTCGCTTTTCTCATTGTGAAACCATGGGCCTCGCAACGACGCTACCTGAGG
ACTCGGCATGAGGTAGTAGCCCTATTTGATCTAATGGTCCTTGATCGGTTTACCTCAGAC
TAGCCGGCTCGCGAGCTGTGTCTGTACACGGTGCGGTTCCGGGAAGATGCTAGTTTTGGC
TGCGTGCCTCTGGGATGAGCGCCTAGTCTAGATACACAGAGGCCTGATCTGCAATCTGCG
AAGACCCTGAAGTTAAGGCCTCCTGCTTATACAGATTCAAAATCTTTTATAATGCGGTGG
CTGGGATAGCAGCTCTCTGTCCATATTAGCGGCTCGCCAAGACGCACCCCGTATTAACGA
TCACGTTACAAGATTTTTAAGTCGAGCGTAGCCCCAATGGTTCTGCAAATGGAATTGCAG
TCCTCCCCTGGCCGAATCGAACCACTGACGCATTTGCGGTACGGC"""
s1 = "".join(s1.split("\n"))
s2 = "GGCTGTCTACAGGGATGGTAGCCGGCGCTTTATTTAGAAACAGCCAGTACCAGCATCGCCCTCTCCTTGCTCTGCTTCACGTTGTGTTAATGATATGG"
 
"""
s1 = "ACGTACGTGACG"
s2 = "GTA"
"""
 
rs = align(s1,s2)
rs = [r+1 for r in rs]
print " ".join(map(str,rs))