protein = "AQSDIEYYTPHLNGLMCEFYMQTFFARAGVLIVDTQNYETHILYCPNVRWDCQTMMQIGSMMVTRCGDIRWQWMHACKDRLVQMPIYMLSEIVLFNPGADFEAWCIIPDMKNWRNSYHFYDVFTFTPRKISQISEGRQHKSGVVAEQRYPIVWNIHQVQICQGPQVKSRCTFMEALGNHQPHNANTRGHIGDKMDVHVITHWKKHVANSPYAERSRGTYCSFTWHGIEPDETDGCGGAMGTINQWMPAKIADRKVFYKVAPSCPGGKVMTERINKDDFIPNWMLPHDVCWNLSMRYHVKECEAWEPHKHQDHQTNSIRSFVPHCQSHEDETKNTMRQKQAIMQCILAIGHHDGKRCSAWTQDMSVKEEPLMFGIAALRNRMARNLSHGFQATTHHMECHKQVKPGTSCARWVDNRPTAMLSGMDSLVVVYCHGNIYLEMWLCCPLTMQMYARQFPYYPYSNEETGNYIAYSNPCIWVSIEKNAKCQMENFQWDDWSPRCGPDQNQWQHARQARSQKLGNYWIVPKRSEPIQNWHHTQEICMLAFRKSDAYDVCTGFKEDEQGRPHQMWRMYIQRWLIEFFIRRNAFAHAQQDTDQVKNCWAKLYDKELMARDEYKMMHMAVMWILMKWVTDPSCHCVISCHCWLHWYESMGDFAVTKEYKHSWVGENSWGMVTSGWQEEKLTFWIWWAMHGGYPVYEELCNPLALSNPHTRGVSIQQERYELMDDMFQIAMAPMMRNGFWQTGEGENKKPFVSDQGCPWLQTSDFTRRHCNLWCASPTESADDVQIPKIGTFVHNGVAAAGYTFLLISTGEFRWHPNTCMAWWWYMINSCGMVESYYSFTISFYMGWEIRIFDIMIEYSYSNMTYYYRADTQDMMHRQDALVAFPQPNEQQYCVFMFGLDNINFTHPADCKFPCL"
mass = 0
for x in protein:
    if x == 'A':
        mass += 71.03711
    if x == 'C':
        mass += 103.00919
    if x == 'D':
        mass += 115.02694
    if x == 'E':
        mass += 129.04259
    if x == 'F':
        mass += 147.06841
    if x == 'G':
        mass += 57.02146
    if x == 'H':
        mass += 137.05891
    if x == 'I':
        mass += 113.08406
    if x == 'K':
        mass += 128.09496
    if x == 'L':
        mass += 113.08406
    if x == 'M':
        mass += 131.04049
    if x == 'N':
        mass += 114.04293
    if x == 'P':
        mass += 97.05276
    if x == 'Q':
        mass += 128.05858
    if x == 'R':
        mass += 156.10111
    if x == 'S':
        mass += 87.03203
    if x == 'T':
        mass += 101.04768
    if x == 'V':
        mass += 99.06841
    if x == 'W':
        mass += 186.07931
    if x == 'Y':
        mass += 163.06333
print("%0.3f" % mass)